---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: tinyauth
spec:
  name: Tinyauth
  callbackUrls:
    - "https://tinyauth.${SECRET_DOMAIN}/api/oauth/callback/pocketid"
  pkceEnabled: true
  instanceSelector:
    matchLabels:
      app.kubernetes.io/name: pocket-id
  secret:
    enabled: true
    name: tinyauth-oidc-secret
    keys:
      clientID: TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID
      clientSecret: TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET
