---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: dragonfly-cluster
spec:
  selector:
    matchLabels:
      app: dragonfly-cluster
  podTargetLabels: ["app"]
  podMetricsEndpoints: [{ port: admin }]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dragonfly-cluster-allow-metrics
  namespace: database
spec:
  podSelector:
    matchLabels:
      app: dragonfly-cluster
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
      ports:
        - port: 9999
          protocol: TCP