---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafananotificationpolicy_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaNotificationPolicy
metadata:
  name: notification-policy
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  route:
    receiver: pushover
    group_by: ["grafana_folder", "alertname"]
    group_wait: 1m
    group_interval: 5m
    repeat_interval: 12h
