---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name donetick-config-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      templateFrom:
        - configMap:
            name: donetick-config-tpl
            items:
              - key: selfhosted.yaml
  dataFrom:
    - extract:
        key: /authentik
    - extract:
        key: /ses-creds
    - extract:
        key: /cnpg-users
    - extract:
        key: /default/donetick
    - extract:
        key: /default/rustfs
