---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name donetick-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        # OAUTH2 — verify exact env var names in donetick docs
        DT_OAUTH2_AUTH_URL: "https://{{ .AUTHENTIK_SSO_SUBDOMAIN }}.${SECRET_DOMAIN}/application/o/authorize/"
        DT_OAUTH2_TOKEN_URL: "https://{{ .AUTHENTIK_SSO_SUBDOMAIN }}${SECRET_DOMAIN}/application/o/token"
        DT_OAUTH2_USER_INFO_URL: "https://{{ .AUTHENTIK_SSO_SUBDOMAIN }}${SECRET_DOMAIN}/application/o/userinfo"
        DT_OAUTH2_REDIRECT_URL: "https://${GATUS_SUBDOMAIN}.${SECRET_DOMAIN}/auth/oauth2"
        DT_OAUTH2_CLIENT_ID: "{{ .DONETICK_OAUTH2_CLIENT_ID }}"
        DT_OAUTH2_CLIENT_SECRET: "{{ .DONETICK_OAUTH2_CLIENT_SECRET }}"
        # SMTP / Amazon SES — verify exact env var names in donetick docs
        # DT_EMAIL_HOST: "{{ .SMTP_HOST }}"
        # DT_EMAIL_PORT: "{{ .SMTP_PORT }}"
        # # Donetick only support api key auth via `DT_EMAIL_KEY`
        # DT_EMAIL_EMAIL: "{{ .SMTP_FROM }}"
        # Database
        DT_DATABASE_HOST: "pgsql-cluster-rw.database.svc.cluster.local"
        DT_DATABASE_PORT: "5432"
        DT_DATABASE_NAME: "${APP}"
        DT_DATABASE_USER: "${APP}"
        DT_DATABASE_PASSWORD: "{{ .donetick_postgres_password }}"
  dataFrom:
    - extract:
        key: /authentik
    - extract:
        key: /ses-creds
    - extract:
        key: /cnpg-users
