---
version: "3.8"

services:
  tailscale:
    image: tailscale/tailscale:v1.94.2@sha256:95e528798bebe75f39b10e74e7051cf51188ee615934f232ba7ad06a3390ffa1
    container_name: tailscale
    restart: unless-stopped
    networks:
      - doco-cd
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    environment:
      TS_AUTHKEY: ${TAILSCALE_AUTH_KEY}
      TS_HOSTNAME: truenas
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: false

networks:
  doco-cd:
    external: true

volumes:
  data:
