---
version: "3.8"

services:
  tailscale:
    image: ghcr.io/tailscale/tailscale:v1.102.5@sha256:c507f3a2a6ab1cabd8d809b98edeb41edbd5c3fb6ad9632ffd098b4c7d0b4065
    container_name: tailscale
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    environment:
      TS_AUTHKEY: ${TAILSCALE_AUTH_KEY}
      TS_AUTH_ONCE: true
      TS_HOSTNAME: truenas
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: false
      TS_EXTRA_ARGS: --advertise-tags=tag:nas

volumes:
  data:
