---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
configMapGenerator:
  - name: llama-cpp-config
    files:
      - ./resources/presets.ini
  - name: llama-cpp-download-script
    files:
      - ./resources/download-model.sh
generatorOptions:
  disableNameSuffixHash: true
