---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: &name actual-oidc-secret
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: akeyless-secret-store
  selector:
    secret:
      name: *name
  data:
    - match:
        secretKey: ACTUAL_OPENID_CLIENT_ID
        remoteRef:
          remoteKey: /security/pocket-id-clients
          property: ACTUAL_OPENID_CLIENT_ID
    - match:
        secretKey: ACTUAL_OPENID_CLIENT_SECRET
        remoteRef:
          remoteKey: /security/pocket-id-clients
          property: ACTUAL_OPENID_CLIENT_SECRET
