---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: actual-oidc
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: akeyless-secret-store
  selector:
    secret:
      name: actual-oidc-secret
  data:
    - match:
        secretKey: ACTUAL_OPENID_CLIENT_ID
        remoteRef:
          remoteKey: /security/pocket-id-clients
          property: ACTUAL_OPENID_CLIENT_ID
    - match:
        secretKey: ACTUAL_OPENID_CLIENT_SECRET
        remoteRef:
          remoteKey: /security/pocket-id-clients
          property: ACTUAL_OPENID_CLIENT_SECRET
