version: 1
host:
  id: "unraid"

devices:
  - device: /dev/sda
    type: sat
  - device: /dev/sdb
    type: sat
  - device: /dev/sdc
    type: sat
  - device: /dev/sdd
    type: sat
  - device: /dev/sde
    type: sat
  - device: /dev/sdf
    type: sat
  - device: /dev/sdg
    type: sat
  - device: /dev/sdh
    type: sat
  - device: /dev/sdi
    type: sat
  - device: /dev/sdj
    type: sat
  - device: /dev/sdk
    type: sat
  - device: /dev/sdl
    type: sat
  - device: /dev/sdm
    type: sat
  - device: /dev/sdn
    type: sat
