---
services:
  scrutiny-collector:
    image: ghcr.io/analogj/scrutiny:v0.9.0-collector@sha256:3ff9e9ba8c0c4dbb83a3537222de8eb1be4115b38a14ec4f57004684973308df
    container_name: scrutiny-collector
    restart: unless-stopped
    cap_add:
      - SYS_RAWIO    # required for smartctl ATA passthrough
      - SYS_ADMIN    # required for smartctl device access
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
      - /dev/sde:/dev/sde
      - /dev/sdf:/dev/sdf
      - /dev/sdg:/dev/sdg
      - /dev/sdh:/dev/sdh
      - /dev/sdi:/dev/sdi
      - /dev/sdj:/dev/sdj
      - /dev/sdk:/dev/sdk
      - /dev/sdl:/dev/sdl
      - /dev/sdm:/dev/sdm
      - /dev/sdn:/dev/sdn
    volumes:
      - /run/udev:/run/udev:ro
    networks:
      - doco-cd
    environment:
      COLLECTOR_API_ENDPOINT: http://scrutiny.internal
      COLLECTOR_HOST_ID: unraid

networks:
  doco-cd:
    external: true
