---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name pocket-id-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        ENCRYPTION_KEY: "{{ .POCKETID_ENCRYPTION_KEY }}"
        MAXMIND_LICENSE_KEY: "{{ .MAXMIND_PANGOLIN_LICENSE_KEY }}"
  data:
    - secretKey: MAXMIND_PANGOLIN_LICENSE_KEY
      remoteRef:
        key: /docker/vps-maxmind/license-key
  dataFrom:
    - extract:
        key: /database/cnpg-users
    - extract:
        key: /security/pocket-id
