---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name pocket-id-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        ENCRYPTION_KEY: "{{ .POCKETID_ENCRYPTION_KEY }}"
        MAXMIND_LICENSE_KEY: "{{ .MAXMIND_PANGOLIN_LICENSE_KEY }}"
        DB_CONNECTION_STRING: |-
          postgres://{{ .${APP} }}:{{ .${APP}_postgres_password }}@${CNPG_NAME:=pgsql-cluster}-rw.database.svc.cluster.local/{{ .${APP} }}

  dataFrom:
    - extract:
        key: /database/cnpg-users
    - extract:
        key: /docker/vps-maxmind/license-key
    - extract:
        key: /security/pocket-id
