---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: flux
spec:
  image: ghcr.io/controlplaneio-fluxcd/flux-operator-mcp:v0.50.0
  transport: stdio
  groupRef:
    name: mcp-ext
  args:
    - serve
    - --read-only
  serviceAccount: flux-mcp-sa