---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name b2-rclone-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        rclone.conf: |
          [b2-kopia]
          type = s3
          secret_access_key = {{ .B2_T0MKUBE_SECRET_ACCESS_KEY }}
          access_key_id = {{ .B2_T0MKUBE_ACCESS_KEY_ID }}
          endpoint = {{ .B2_ENDPOINT }}
          provider = Other
          region = {{ .B2_REGION }}
  dataFrom:
    - extract:
        key: /cloud-providers/b2-creds
