---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app zwave
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      *app :
        containers:
          app:
            image:
              repository: ghcr.io/zwave-js/zwave-js-ui
              tag: 11.16.2@sha256:c43f88e2e395bb4b37c9e87e64998b751b1e1908318177623cebe08867e1eb42
            env:
              TZ: ${TIMEZONE}
              PORT: &port 80
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: ${GATUS_PATH}
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              privileged: true # needed for zwave-js to access the usb device
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
        pod:
          hostUsers: true
          nodeSelector:
            feature.node.kubernetes.io/usb-zwave: "true"
    service:
      app:
        ports:
          http:
            port: *port
          websocket:
            port: 3000
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /usr/src/app/store
      usb:
        type: hostPath
        hostPath: /dev/serial/by-id/usb-0658_0200-if00
        hostPathType: CharDevice
        globalMounts:
          - path: /dev/zwave
      tmp:
        type: emptyDir

