---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${APP}"
spec:
  sourcePVC: "${VOLSYNC_CLAIM:-${APP}}"
  trigger:
    schedule: "${VOLSYNC_SCHEDULE:=0 */6 * * *}"
  kopia:
    accessModes: ["${VOLSYNC_SNAP_ACCESSMODES:=ReadWriteOnce}"]
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:=ReadWriteOnce}"]
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:=5Gi}"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:=openebs-hostpath}"
    compression: zstd-fastest
    copyMethod: "${VOLSYNC_COPYMETHOD:=Snapshot}"
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      fsGroup: ${VOLSYNC_PGID:=1000}
    moverVolumes:
      - mountPath: repository
        volumeSource:
          nfs:
            server: clonenas.internal
            path: /mnt/vault/backups/kubernetes/kopia
    parallelism: 2
    repository: "${APP}-volsync-secret"
    retain:
      hourly: 8
      daily: 7
    storageClassName: "${VOLSYNC_STORAGECLASS:=ceph-ssd}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:=csi-ceph-blockpool}"
