---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cleanrr
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      *app :
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/zariel/cleanrr
              tag: v0.1.7@sha256:b5a7a2ac327327daf4fb7ed6fb89997b8aa5527867684b29de381c58ebabad26
            env:
              CLEANRR_DRY_RUN: true
              CLEANRR_MINIMUM_AGE: 30m
              CLEANRR_POLL_INTERVAL: 2m
              CLEANRR_SERVERS__RADARR__URL: http://radarr.media.svc.cluster.local:7878
              CLEANRR_SERVERS__SONARR__URL: http://sonarr.media.svc.cluster.local:8989
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec: &probeSpec
                  httpGet:
                    path: /health/live
                    port: &port 8080
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                <<: *probes
                spec:
                  <<: *probeSpec
                  httpGet:
                    path: /health/ready
                    port: *port
                  periodSeconds: 10
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health/startup
                    port: *port
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        endpoints:
          - port: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
