---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app toolhive-operator-crds
spec:
  interval: 1h
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: toolhive-operator-crds
      namespace: &ns ai
  path: ./kubernetes/apps/ai/toolhive/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *ns
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app toolhive-operator
spec:
  dependsOn:
    - name: toolhive-operator-crds
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: &ns ai
  interval: 1h
  path: ./kubernetes/apps/ai/toolhive/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *ns
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app toolhive-operator-config
spec:
  dependsOn:
    - name: toolhive-operator-crds
    - name: secret-stores
      namespace: external-secrets
    - name: dragonfly-cluster
      namespace: database
  interval: 1h
  path: ./kubernetes/apps/ai/toolhive/config
  postBuild:
    substitute:
      APP: *app
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
      - kind: Secret
        name: toolhive-secret
        optional: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ai
  wait: false
