---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name litellm-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        # App
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}"
        # API
        LLAMA_API_KEY: '{{ .LLAMA_API_KEY }}'
  dataFrom:
    - extract:
        key: /ai/litellm
    - extract:
        key: /ai/llama-cpp
