---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name litellm-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        # App
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}"
        PROXY_ADMIN_ID: "{{ .LITELLM_ADMIN_USER }}"
        # API
        LLAMA_API_KEY: '{{ .LLAMA_API_KEY }}'
        # SSO
        GENERIC_SCOPE: openid profile email groups
        GENERIC_CLIENT_ID: "{{ .LITELLM_OIDC_CLIENT_ID }}"
        GENERIC_CLIENT_SECRET: "{{ .LITELLM_OIDC_CLIENT_SECRET }}"
        GENERIC_AUTHORIZATION_ENDPOINT: "https://{{ .AUTHENTIK_SSO_SUBDOMAIN }}.${SECRET_DOMAIN}/application/o/authorize/"
        GENERIC_TOKEN_ENDPOINT: "https://{{ .AUTHENTIK_SSO_SUBDOMAIN }}.${SECRET_DOMAIN}/application/o/token/"
        GENERIC_USERINFO_ENDPOINT: "https://{{ .AUTHENTIK_SSO_SUBDOMAIN }}.${SECRET_DOMAIN}/application/o/userinfo/"
  dataFrom:
    - extract:
        key: /ai/litellm
    - extract:
        key: /ai/llama-cpp
    - extract:
        key: /default/authentik
