---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./litellmproxy.yaml
  - ./litellmmodels.yaml
  - ./llama-qwen.yaml
  - ./llama-gemma.yaml
  - ./litellmmcpservers.yaml
  - ./mcp-secrets.yaml
  # - ./mcp-flux-rbac.yaml
  # - ./mcp-kubectl-rbac.yaml
  - ./mcp-talos-serviceaccount.yaml
  - ./servicemonitor.yaml
