# Grafana service account for MCP is created in grafana instance.
# TODO: Emberstack reflector needed in kube-system ns to replicate the secret to ai ns.
# ---
# # yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: &name grafana-mcp
# spec:
#   refreshInterval: 5m
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: akeyless-secret-store
#   target:
#     name: *name
#     creationPolicy: Owner
#   data:
#     - secretKey: token
#       remoteRef:
#         key: /observability/grafana-mcp
#         property: token
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name github-mcp
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: /kubernetes/konflate
        property: KONFLATE_TOKEN
