---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/pocketid.internal/pocketidoidcclient_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: litellm
spec:
  name: LiteLLM
  callbackUrls:
    - "https://${APP}.${SECRET_DOMAIN}/sso/callback"
  launchUrl: "https://${APP}.${SECRET_DOMAIN}/ui/"
  logo:
    logoUrl: "https://cdn.jsdelivr.net/gh/selfhst/icons@main/webp/litellm.webp"
  pkceEnabled: false
  allowedUserGroups:
    - name: id-admin
      namespace: security
    - name: id-home
      namespace: security
    - name: id-family
      namespace: security
  secret:
    enabled: true
    name: litellm-oidc-secret
    keys:
      clientID: GENERIC_CLIENT_ID
      clientSecret: GENERIC_CLIENT_SECRET
      authorizationUrl: GENERIC_AUTHORIZATION_ENDPOINT
      tokenUrl: GENERIC_TOKEN_ENDPOINT
      userinfoUrl: GENERIC_USERINFO_ENDPOINT
