---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name kite-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        KITE_ENCRYPT_KEY: "{{ .KITE_ENCRYPT_KEY }}"
        JWT_SECRET: "{{ .KITE_JWT_SECRET }}"
  dataFrom:
  - extract:
      key: /default/authentik
  - extract:
      key: /kubernetes/kubeconfig
  - extract:
      key: /observability/kite
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name kite-config-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      templateFrom:
        - configMap:
            name: kite-config-tpl
            items:
              - key: config.yaml
  dataFrom:
  - extract:
      key: /default/authentik
  - extract:
      key: /observability/kite
  - extract:
      key: /kubernetes/kubeconfig
  - extract:
      key: /talos-m70q
