---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kite
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.4.0@sha256:ebd9d30add17acdf935d73eb004758c7dfd9388aaa605fda70ad74378ab92aec
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-initdb-secret"
        containers:
          app:
            image:
              repository: ghcr.io/kite-org/kite
              tag: v0.14.0@sha256:65517749ea2fbcd8faa6d402a53a9b6d6ccf94ac64b3fb43ad5773051dc251b8
            env:
              HOST: https://${GATUS_SUBDOMAIN}.${SECRET_DOMAIN}
              ENABLE_ANALYTICS: true
              KITE_CONFIG_FILE: /kite/config.yaml
              DB_TYPE: postgres
              DB_DSN:
                valueFrom:
                  secretKeyRef:
                    name: &pg "{{ .Release.Name }}-pguser-secret"
                    key: dsn
              DEBUG: true
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: ${GATUS_PATH}
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
        serviceAccount:
          identifier: *app
    defaultPodOptions:
      automountServiceAccountToken: true
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: http
    route:
      app:
        hostnames: ["${GATUS_SUBDOMAIN}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        type: emptyDir
      config-files:
        type: secret
        name: "{{ .Release.Name }}-config-secret"
        globalMounts:
          - path: /kite
    rbac:
      bindings:
        *app :
          type: ClusterRoleBinding
          roleRef:
            kind: ClusterRole
            name: *app
          subjects:
            - kind: ServiceAccount
              name: *app
              namespace: "{{ .Release.Namespace }}"
