---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
# https://github.com/tholinka/home-ops/blob/main/kubernetes/apps/media/qbittorrent/app/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app seanime
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-config:
            image:
              repository: ghcr.io/home-operations/busybox
              tag: 1.38.0@sha256:7e2c04dd50ede647bf4a7a4c8dbd629dd4971cd139b9b88fb22bfc3c7a6c13df
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              runAsNonRoot: true
            command:
              - sh
              - -c
              - |
                set -euo pipefail
                mkdir -p /home/seanime/.config/Seanime
                cp /run/config/config.toml /home/seanime/.config/Seanime/config.toml
        containers:
          app:
            image:
              repository: ghcr.io/ju1-js/seanime
              tag: v3.9.1-hwaccel@sha256:bbb73ec0f612b2273c70e0af179280715d130f0868c33a1dfb4d80f77053cdf8
            env:
              SEANIME_SERVER_HOST: 0.0.0.0
              SEANIME_SERVER_PORT: &port 80
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec: &probeSpec
                  httpGet:
                    path: /
                    port: *port
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                <<: *probes
                spec:
                  <<: *probeSpec
                  periodSeconds: 10
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              claims:
                - name: gpu
              requests:
                cpu: "1"
                memory: 1Gi
              limits:
                cpu: "2"
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: *app
      annotations:
        k8s.v1.cni.cncf.io/networks: |-
          [{
            "name": "vpn",
            "namespace": "network",
            "ips": ["192.168.99.100/24"],
            "mac": "0e:df:3a:a8:d8:ba"
          }]
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: Always
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["${GATUS_SUBDOMAIN}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    configMaps:
      config:
        data:
          config.toml: |-
            version = '3.9.1'

            [cache]
            dir = '/cache'
            transcodedir = '/cache/transcode'

            [database]
            name = 'seanime'

            [extensions]
            dir = '$SEANIME_DATA_DIR/extensions'

            [logs]
            dir = '$SEANIME_DATA_DIR/logs'

            [anime]
            downloaddir = '/media/anime'

            [manga]
            downloaddir = '/media/manga'
            localdir = '$SEANIME_DATA_DIR/manga-local'

            [offline]
            assetdir = '$SEANIME_DATA_DIR/offline/assets'
            dir = '$SEANIME_DATA_DIR/offline'

            [server]
            host = '0.0.0.0'
            offline = false
            port = 80
            usebinarypath = true
            secureMode = 'lax'

            [torrent]
            dir = '/media/downloads/completed/seanime'

            [web]
            assetdir = '$SEANIME_DATA_DIR/assets'
    persistence:
      config:
        existingClaim: *app
        advancedMounts:
          *app :
            init-config:
              - path: /home/seanime/.config
            app:
              - path: /home/seanime/.config
      configmap:
        type: configMap
        identifier: config
        defaultMode: 0644
        advancedMounts:
          *app :
            init-config:
              - path: /run/config/config.toml
                subPath: config.toml
                readOnly: true
      media:
        type: nfs
        server: truenas.internal
        path: /mnt/nas/data/media
        globalMounts:
          - path: /media
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
          - path: /cache
            subPath: cache
