---
working_dir: ./docker/vps
auto_discovery:
  enabled: true
  depth: 1
  delete: true
# Must be stored as individual text-based static secrets in aKeyless (not JSON)
external_secrets:
  DOMAIN:
    store_ref: akeyless
    remote_ref:
      key: docker/secret-domain
  PROMETHEUS_USERNAME:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-prometheus/username
  PROMETHEUS_PASSWORD:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-prometheus/password
  MONGO_INITDB_ROOT_USERNAME:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-unifi/mongo-root-username
  MONGO_INITDB_ROOT_PASSWORD:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-unifi/mongo-root-password
  MONGO_USER:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-unifi/mongo-user
  MONGO_PASS:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-unifi/mongo-pass
  RESTIC_REPOSITORY:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-unifi/restic-repository
  RESTIC_PASSWORD:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-unifi/restic-password
  B2_ACCOUNT_ID:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-unifi/b2-account-id
  B2_ACCOUNT_KEY:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-unifi/b2-account-key
  UNIFI_HOSTNAME:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-unifi/hostname
  TOWONEL_HUB_HOSTNAME:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-towonel/hub-hostname
  TOWONEL_IDENTITY_KEY:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-towonel/identity-key
  TOWONEL_HUB_KEK:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-towonel/hub-kek
  TOWONEL_INVITE_HASH_KEY:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-towonel/invite-hash-key
  TOWONEL_HUB_OPERATOR_API_KEY:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-towonel/operator-api-key
  TOWONEL_HUB_LINK_PSK:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-towonel/hub-link-psk
  CADDY_ACME_EMAIL:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-towonel/acme-email
  CROWDSEC_ENROLL_KEY:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-crowdsec/enroll-key
  HOME_IP_CIDR:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-crowdsec/home-ip-cidr
force_recreate: false
reconciliation:
  enabled: true
  events: ["unhealthy", "die"]
