---
working_dir: ./docker/vps
auto_discovery:
  enabled: true
  depth: 1
  delete: true
# Must be stored as individual text-based static secrets in aKeyless (not JSON)
external_secrets:
  PANGOLIN_SERVER_SECRET:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-pangolin/secret-domain
  CF_CLOUDFLARE_TOKEN:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-cloudflare/dns-token
  CROWDSEC_TRAEFIK_API_KEY:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-pangolin/crowdsec-traefik-api-key
  HOME_IP_CIDR:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-pangolin/home-ip-cidr
  MAXMIND_ACCOUNT_ID:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-maxmind/account-id
  MAXMIND_PANGOLIN_LICENSE_KEY:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-maxmind/license-key
  DOMAIN:
    store_ref: akeyless
    remote_ref:
      key: docker/secret-domain
  PROMETHEUS_USERNAME:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-prometheus/username
  PROMETHEUS_PASSWORD:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-prometheus/password
  MONGO_INITDB_ROOT_USERNAME:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-unifi/mongo-root-username
  MONGO_INITDB_ROOT_PASSWORD:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-unifi/mongo-root-password
  MONGO_USER:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-unifi/mongo-user
  MONGO_PASS:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-unifi/mongo-pass
  RESTIC_REPOSITORY:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-unifi/restic-repository
  RESTIC_PASSWORD:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-unifi/restic-password
  B2_ACCOUNT_ID:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-unifi/b2-account-id
  B2_ACCOUNT_KEY:
    store_ref: akeyless
    remote_ref:
      key: docker/vps-unifi/b2-account-key
force_recreate: false
reconciliation:
  enabled: true
  events: ["unhealthy", "die"]
