---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name grimmory-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        MARIADB_PASSWORD: &dbpass "{{ .GRIMMORY_MARIADB_PASSWORD }}"
        DATABASE_PASSWORD: *dbpass
        MARIADB_ROOT_PASSWORD: "{{ .GRIMMORY_MARIADB_ROOT_PASSWORD }}"
  dataFrom:
    - extract:
        key: /media/grimmory
