---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/pocketid.internal/pocketidoidcclient_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: grimmory
spec:
  name: Grimmory
  callbackUrls:
    - "https://${GATUS_SUBDOMAIN}.${SECRET_DOMAIN}/oauth2-callback"
  launchUrl: "https://${GATUS_SUBDOMAIN}.${SECRET_DOMAIN}/"
  pkceEnabled: false
  allowedUserGroups:
    - name: id-admin
      namespace: security
    - name: id-home
      namespace: security
    - name: id-family
      namespace: security
  secret:
    enabled: true
    name: grimmory-oidc-secret
    keys:
      clientID: GRIMMORY_OIDC_CLIENT_ID
      clientSecret: GRIMMORY_OIDC_CLIENT_SECRET
      issuerUrl: GRIMMORY_OIDC_ISSUER_URL
