[botdetection]
ipv4_prefix = 32
ipv6_prefix = 48
trusted_proxies = [
  '127.0.0.0/8',
  '::1',
  '10.0.0.0/8',
  '192.168.0.0/16',
]

[botdetection.ip_limit]
filter_link_local = true
link_token = false        # MUST be false for headless API clients like open-webui

[botdetection.ip_lists]
block_ip = []
pass_ip = [
  '10.0.0.0/8',           # pod CIDR + cluster traffic
  '192.168.0.0/16',       # LAN clients
]

pass_searxng_org = false