---
use_default_settings: true

server:
  public_instance: false
  limiter: true
  image_proxy: true
  method: GET # https://github.com/searxng/searxng/pull/3619

outgoing:
  request_timeout: 10.0
  max_redirects: 5
  pool_connections: 20
  pool_maxsize: 10

general:
  instance_name: SearXNG
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: false

search:
  autocomplete: duckduckgo
  favicon_resolver: duckduckgo
  autocomplete_min: 2
  languages:
    - en
    - en-US
  formats:
    - html
    - json
  max_ban_time_on_fail: 5
  ban_time_on_fail: 5
  suspended_times:
    SearxEngineAccessDeniedException: 180
    SearxEngineTooManyRequestsException: 180
    SearxEngineCaptchaException: 0
  safe_search: 0

ui:
  static_use_hash: true
  default_theme: simple
  theme_args:
    simple_style: auto
  infinite_scroll: true
  results_on_new_tab: false
  query_in_title: true

categories_as_tabs:
  general:
  images:
  videos:
  map:

enabled_plugins:
  - Basic Calculator
  - Hash plugin
  - Hostnames plugin
  - Open Access DOI rewrite
  - Self Informations
  - Tracker URL remover
  - Unit converter plugin

hostnames:
  high_priority:
    - (.*)\/blog\/(.*)
    - (.*\.)?wikipedia.org$
    - (.*\.)?github.com$
    - (.*\.)?reddit.com$
    - (.*\.)?docker.com$
    - (.*\.)?archlinux.org$
    - (.*\.)?stackoverflow.com$
    - (.*\.)?askubuntu.com$
    - (.*\.)?superuser.com$

engines:
  - name: duckduckgo
    disabled: true
    weight: 3
  - name: google
    disabled: false
    weight: 2
  - name: wikipedia
    disabled: false
    weight: 1
  - name: brave
    disabled: true  # getting 429s, must be disabled
