---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name esphome-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        secrets.yaml: |-
          wifi_ssid: "{{ .IOT_WIFI_SSID }}"
          wifi_pwd: "{{ .IOT_WIFI_PASSWORD }}"

          time_timezone: "${TIMEZONE}"
          time_update_interval: "6h"

          domain_devices: .internal

          api_encryption_key: "{{ .ESPHOME_API_ENCRYPTION_KEY }}"
  dataFrom:
    - extract:
        key: /network/iot-wifi
    - extract:
        key: /home-automation/esphome
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name esphome-deploykey
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
  data:
    - secretKey: id_ed25519
      remoteRef:
        key: /home-automation/esphome
        property: GITHUB_DEPLOY_KEY
