---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name towonel-agent-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        TOWONEL_INVITE_TOKEN: "{{ .invite_token }}"
        TOWONEL_VPS_IP: "{{ .towonel_vps_ip }}"
  data:
    - secretKey: invite_token
      remoteRef:
        key: /network/towonel-agent
        property: invite_token
    - secretKey: towonel_vps_ip
      remoteRef:
        key: docker/vps-towonel/ip
