---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name memini-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        MEMINI_API_KEY: "{{ .MEMINI_ADMIN_API_KEY }}"
  dataFrom:
    - extract:
        key: /ai/memini
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name memini-api-keys
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        api-keys.yaml:
          | # https://git.erwanleboucher.dev/eleboucher/memini/src/branch/main/docs/guides/homelab-team.md
          keys:
          - name: hermes
            secret: {{ .MEMINI_HERMES_API_KEY }}
            home: tscibilia/personal
            default_namespace: tscibilia/hermes
            admin: false
          - name: opencode
            secret: {{ .MEMINI_OPENCODE_API_KEY }}
            home: tscibilia/personal
            default_namespace: tscibilia/opencode
            admin: false
  dataFrom:
    - extract:
        key: /ai/memini
