---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name rustfs-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        RUSTFS_ACCESS_KEY: "{{ .RUSTFS_ROOT_USER }}"
        RUSTFS_SECRET_KEY: "{{ .RUSTFS_ROOT_PASSWORD }}"
        RUSTFS_IDENTITY_OPENID_CLIENT_ID: "{{ .RUSTFS_OPENID_CLIENT_ID }}"
        RUSTFS_IDENTITY_OPENID_CLIENT_SECRET: "{{ .RUSTFS_OPENID_CLIENT_SECRET }}"
        RUSTFS_IDENTITY_OPENID_CONFIG_URL: "https://auth.${SECRET_DOMAIN}/application/o/${GATUS_SUBDOMAIN}/.well-known/openid-configuration"
  dataFrom:
    - extract:
        key: /default/rustfs
    - extract:
        key: /authentik
