---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name toolhive-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        # App
        EC_SIGNING_KEY: "{{ .EC_SIGNING_KEY }}"
        HMAC_KEY: "{{ .HMAC_KEY }}"
        # OIDC
        OIDC_CLIENT_SECRET: "{{ .TOOLHIVE_OIDC_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: /ai3090/toolhive
    - extract:
        key: /default/authentik
