---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/virtualmcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: VirtualMCPServer
metadata:
  name: mcp-gateway-ext
spec:
  authServerConfig:
    issuer: https://mcp.${SECRET_DOMAIN}
    signingKeySecretRefs:
      - name: toolhive-secret
        key: EC_SIGNING_KEY
    hmacSecretRefs:
      - name: toolhive-secret
        key: HMAC_KEY
    tokenLifespans:
      accessTokenLifespan: 1h
      refreshTokenLifespan: 168h
      authCodeLifespan: 10m
    upstreamProviders:
      - name: authentik
        type: oidc
        oidcConfig:
          issuerUrl: https://${AUTHENTIK_SSO_SUBDOMAIN}.${SECRET_DOMAIN}/application/o/toolhive/
          clientId: toolhive
          clientSecretRef:
            name: toolhive-secret
            key: OIDC_CLIENT_SECRET
          redirectUri: https://mcp.${SECRET_DOMAIN}/oauth/callback
          scopes:
            - openid
            - profile
            - email
            - offline_access
  config:
    aggregation:
      conflictResolution: prefix
      conflictResolutionConfig:
        prefixFormat: "{workload}."
  # telemetryConfigRef:
  #   name: prometheus
  groupRef:
    name: mcp-ext
  incomingAuth:
    type: oidc
    oidcConfigRef:
      name: authentik
      audience: https://mcp.${SECRET_DOMAIN}/mcp
      resourceUrl: https://mcp.${SECRET_DOMAIN}/mcp
      scopes:
        - openid
        - profile
        - email
        - offline_access
  outgoingAuth:
    source: discovered
  sessionStorage:
    address: dragonfly-cluster.database.svc.cluster.local:6379
    db: 4
    provider: redis
    keyPrefix: "vmcp-sessions:"
  podTemplateSpec:
    spec:
      containers:
        - name: vmcp
          env:
            - name: INSECURE_DISABLE_URL_VALIDATION
              value: "true"
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/virtualmcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: VirtualMCPServer
metadata:
  name: mcp-gateway-int
spec:
  config:
    aggregation:
      conflictResolution: prefix
      conflictResolutionConfig:
        prefixFormat: "{workload}."
  embeddingServerRef:
    name: mcp-tools-embedding
  groupRef:
    name: mcp-int
  incomingAuth:
    type: anonymous
  outgoingAuth:
    source: discovered
  # telemetryConfigRef:
  #   name: prometheus