---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name gatus-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        PUSHOVER_ALERTMANAGER_TOKEN: "{{ .PUSHOVER_ALERTMANAGER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        DB_URI: "postgresql://${APP}:{{ .gatus_postgres_password }}@pgsql-cluster.database.svc.cluster.local:5432/${APP}"
  dataFrom:
    - extract:
        key: /observability/gatus
    - extract:
        key: /database/cnpg-users