---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app gatus
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    fullnameOverride: gatus
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
    initContainers:
      - name: 01-init-db
        image: ghcr.io/home-operations/postgres-init:18.4.0@sha256:5086f94abc783f1147d7c2a32c01db00ab594820026e4f6a82ac2af3dbde7fc7
        envFrom:
          - secretRef:
              name: "{{ .Release.Name }}-initdb-secret"
    gatus:
      delayStartSeconds: "5"
      port: &port 80
      env:
        GATUS_SUBDOMAIN: ${GATUS_SUBDOMAIN}
        SECRET_DOMAIN: ${SECRET_DOMAIN}
      envFrom:
        - secretRef:
            name: "{{ .Release.Name }}-secret"
    sidecar:
      enabled: true
      kinds:
        httproute:
          enable: true
          auto: true
        service:
          enable: true
    httpRoute:
      enabled: true
      annotations:
        gatus.home-operations.com/enabled: "false"
      hostnames: ["${GATUS_SUBDOMAIN}.${SECRET_DOMAIN}"]
      parentRefs:
        - name: envoy-external
          namespace: network
    monitoring:
      serviceMonitor:
        enabled: true
    config:
      existingConfigMap: "{{ .Release.Name }}-configmap"
      items:
        - key: config.yaml
          path: config.yaml
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 512Mi
