---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name scrutiny-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        # scrutiny-web notification env vars
        SCRUTINY_NOTIFY_PUSHOVER_API_KEY: "{{ .SCRUTINY_PUSHOVER_TOKEN }}"
        SCRUTINY_NOTIFY_PUSHOVER_USER_KEY: "{{ .SCRUTINY_PUSHOVER_USER }}"
        # scrutiny-web influxdb connection
        SCRUTINY_WEB_INFLUXDB_TOKEN: "{{ .INFLUXDB_ADMIN_TOKEN }}"
        # influxdb init env vars
        DOCKER_INFLUXDB_INIT_PASSWORD: "{{ .INFLUXDB_ADMIN_PASSWORD }}"
        DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "{{ .INFLUXDB_ADMIN_TOKEN }}"
  dataFrom:
    - extract:
        key: /observability/scrutiny
