---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name rahoot-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        MANAGER_PASSWORD: "{{ .RAHOOT_MANAGER_PASSWORD }}"
  dataFrom:
    - extract:
        key: /default/rahoot
