---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app text-embeddings
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      *app :
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/huggingface/text-embeddings-inference
              tag: cpu-latest@sha256:7f8cbd5fbf27d1ad82450b68ec37e542bbfb0d03e6dc79d6d00242022f2fc4c7
            args:
              - --model-id
              - sentence-transformers/all-MiniLM-L6-v2
              - --port
              - "8080"
              - --hostname
              - 0.0.0.0
              - --huggingface-hub-cache
              - /data
              - --auto-truncate
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec: &probeSpec
                  httpGet:
                    path: /health
                    port: &port 8080
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                <<: *probes
                spec:
                  <<: *probeSpec
                  periodSeconds: 10
              startup:
                enabled: true
                custom: true
                spec:
                  <<: *probeSpec
                  failureThreshold: 10
                  periodSeconds: 30
                  timeoutSeconds: 1
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: "2"
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    persistence:
      data:
        type: emptyDir
        globalMounts:
          - path: /data
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
