---
working_dir: ./docker/truenas
auto_discover: true
auto_discover_opts:
  depth: 1
  delete: true

external_secrets:
  # Must be stored as folders with a single (text-based) static secret file, no JSON!
  TAILSCALE_AUTH_KEY: /truenas/tailscale/auth-key
  SECRET_DOMAIN: /truenas/secret-domain
