---
working_dir: ./docker/truenas
auto_discover: true
auto_discover_opts:
  depth: 1
  delete: true

external_secrets:
  TAILSCALE_AUTH_KEY:
    store_ref: akeyless
    remote_ref:
      key: /truenas/tailscale/auth-key
