---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kometa
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        type: cronjob
        cronjob:
          schedule: "30 2 * * *"
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        initContainers:
          01-init-overlays:
            image:
              repository: docker.io/rustfs/rc
              tag: v0.1.36@sha256:ab024bfebee49a750ce886b4c70963ccd9ddaa03f491704a90710641d7a26699
            command: ["/bin/sh", "-c"]
            env:
              HOME: /tmp
            args:
              - |
                mkdir -p /config/overlays;
                mkdir -p /config/assets;
                rc alias set s3 https://s3.t0m.co --anonymous;
                rc mirror s3/t0m-public/kometa/overlays/ /config/overlays/ --overwrite --remove;
                rc mirror s3/t0m-public/kometa/assets/ /config/assets/ --overwrite --remove
        containers:
          app:
            image:
              repository: docker.io/kometateam/kometa
              tag: v2.5.2@sha256:06e498cded70c9815522c6b2d8708b31759c1e37714746d1eeb56f1e40a8fd95
            command:
              - /bin/sh
              - -c
            args:
              - |
                python3 kometa.py --run --read-only-config --run-libraries "Anime";
                python3 kometa.py --run --read-only-config --run-libraries "Movies";
                python3 kometa.py --run --read-only-config --run-libraries "TV Shows";
            env:
              KOMETA_READ_ONLY_CONFIG: true
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 100m
                memory: 1Gi
              limits:
                cpu: 2000m
                memory: 6Gi # Usage peaks at 4.2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values: ["plex"]
              topologyKey: kubernetes.io/hostname
    persistence:
      config:
        existingClaim: *app
      config-file:
        type: configMap
        name: "{{ .Release.Name }}-configmap"
        globalMounts:
          - path: /config/config.yml
            subPath: config.yml
            readOnly: true
      tmpfs:
        type: emptyDir
        advancedMounts:
          *app :
            app:
              - path: /config/logs
                subPath: logs
