---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name tracearr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        COOKIE_SECRET: "{{ .TRACEARR_COOKIE_SECRET }}"
        JWT_SECRET: "{{ .TRACEARR_JWT_SECRET }}" # retired in a later cleanup release
        BETTER_AUTH_SECRET: "{{ .TRACEARR_JWT_SECRET }}"
        # POSTGRES
        INIT_POSTGRES_DBNAME: "${APP}"
        INIT_POSTGRES_USER: "${APP}"
        INIT_POSTGRES_PASS: "{{ .${APP}_postgres_password }}"
        INIT_POSTGRES_HOST: "${CNPG_NAME:=pgsql-cluster}-rw.database.svc.cluster.local"
        DATABASE_URL: "postgres://${APP}:{{ .${APP}_postgres_password }}@${CNPG_NAME:=pgsql-cluster}-rw.database.svc.cluster.local:5432/${APP}"
  dataFrom:
    - extract:
        key: /media/tracearr
    - extract:
        key: /database/cnpg-users
