---
http:
  middlewares:
    crowdsec:
      plugin:
        crowdsec:
          clientTrustedIPs:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
            - 100.100.0.0/16
          crowdsecAppsecBodyLimit: 10485760
          crowdsecAppsecEnabled: true
          crowdsecAppsecFailureBlock: true
          crowdsecAppsecHost: crowdsec:7422
          crowdsecAppsecUnreachableBlock: true
          crowdsecLapiHost: crowdsec:8080
          crowdsecLapiKey: {{ env "CROWDSEC_API_KEY" }}
          crowdsecLapiScheme: http
          crowdsecMode: stream
          defaultDecisionSeconds: 60
          enabled: true
          httpTimeoutSeconds: 10
          logLevel: INFO
          updateIntervalSeconds: 60
          updateMaxFailure: 5
    default-whitelist:
      ipWhiteList:
        sourceRange:
          - 10.0.0.0/8
          - 192.168.0.0/16
          - 172.16.0.0/12
    badger:
      plugin:
        badger:
          disableForwardAuth: true
    redirect-to-https:
      redirectScheme:
        scheme: https
    security-headers:
      headers:
        contentTypeNosniff: true
        customFrameOptionsValue: SAMEORIGIN
        customResponseHeaders:
          Server: ""
          X-Forwarded-Proto: https
          X-Powered-By: ""
        forceSTSHeader: true
        hostsProxyHeaders:
          - X-Forwarded-Host
        referrerPolicy: strict-origin-when-cross-origin
        sslProxyHeaders:
          X-Forwarded-Proto: https
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 63072000
  routers:
    main-app-router-redirect:
      rule: "Host(`tun.t0m.co`)"
      service: next-service
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
        - badger
    next-router:
      rule: "Host(`tun.t0m.co`) && !PathPrefix(`/api/v1`)"
      service: next-service
      entryPoints:
        - websecure
      middlewares:
        - badger
      tls:
        certResolver: letsencrypt
        domains:
          - main: "t0m.co"
            sans:
              - "*.t0m.co"
    api-router:
      rule: "Host(`tun.t0m.co`) && PathPrefix(`/api/v1`)"
      service: api-service
      entryPoints:
        - websecure
      middlewares:
        - badger
      tls:
        certResolver: letsencrypt
    int-api-router:
      rule: "Host(`api.tun.t0m.co`)"
      service: int-api-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
    ws-router:
      rule: "Host(`tun.t0m.co`)"
      service: api-service
      entryPoints:
        - websecure
      middlewares:
        - badger
      tls:
        certResolver: letsencrypt
    doco-cd-redirect:
      rule: "Host(`doco.tun.t0m.co`)"
      service: doco-cd-svc
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
    doco-cd-router:
      rule: "Host(`doco.tun.t0m.co`)"
      service: doco-cd-svc
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    next-service:
      loadBalancer:
        servers:
          - url: "http://pangolin:3002"
    api-service:
      loadBalancer:
        servers:
          - url: "http://pangolin:3000"
    int-api-service:
      loadBalancer:
        servers:
          - url: "http://pangolin:3003"
    doco-cd-svc:
      loadBalancer:
        servers:
          - url: "http://doco-cd:8880"
