---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name ts-exit-node-0
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    creationPolicy: Orphan # ESO will create if it doesn't exist, but won't overwrite/delete it
    template:
      data:
        _current-profile: "{{ .TS_EXIT_CURRENT_PROFILE }}"
        _machinekey: "{{ .TS_EXIT_MACHINEKEY }}"
        _profiles: "{{ .TS_EXIT_PROFILES }}"
        profile-dfd6: "{{ .TS_EXIT_PROFILE_DATA }}"   # This suffix will change if it re-registers
        authkey: "{{ .TS_NODE_AUTHKEY }}"
  dataFrom:
    - extract:
        key: /network/tailscale/exit-node
    - extract:
        key: /network/tailscale/authkey
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name ts-p1g6-egress-0
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    creationPolicy: Orphan # ESO will create if it doesn't exist, but won't overwrite/delete it
    template:
      data:
        _current-profile: "{{ .TS_P1G6_CURRENT_PROFILE }}"
        _machinekey: "{{ .TS_P1G6_MACHINEKEY }}"
        _profiles: "{{ .TS_P1G6_PROFILES }}"
        profile-4b53: "{{ .TS_P1G6_PROFILE_DATA }}"   # This suffix will change if it re-registers
        authkey: "{{ .TS_NODE_AUTHKEY }}"
  dataFrom:
    - extract:
        key: /network/tailscale/p1g6-egress
    - extract:
        key: /network/tailscale/authkey
