---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/apps/statefulset_v1.json
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: &app ts-ai3090-node
spec:
  serviceName: *app
  replicas: 1
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:
      serviceAccountName: proxies
      nodeSelector:
        feature.node.kubernetes.io/pci-10de.present: "true"
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      containers:
        - name: tailscale
          image: ghcr.io/tailscale/tailscale:v1.98.4@sha256:25cde9ad76020b0e29229136d0c38b5962e9a0e1774ffac9b0df68e4a37d6cf0
          env:
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: ts-ai3090-node-0
                  key: authkey
            - name: TS_KUBE_SECRET
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # → ts-ai3090-node-0
            - name: TS_HOSTNAME
              value: ai3090
            - name: TS_USERSPACE
              value: "true"
            - name: TS_SERVE_CONFIG
              value: /serve/serve.json
          volumeMounts:
            - name: serve-config
              mountPath: /serve
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
            capabilities: { drop: ["ALL"], add: ["NET_ADMIN", "NET_RAW"] }
            seccompProfile: { type: Unconfined }
      volumes:
        - name: serve-config
          configMap:
            name: ts-ai3090-node-serve
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ts-ai3090-node-serve
data:
  serve.json: |
    {
      "TCP": {
        "443": {
          "HTTPS": true
        }
      },
      "Web": {
        "$${TS_CERT_DOMAIN}:443": {
          "Handlers": {
            "/": {
              "Proxy": "http://llama-cpp.ai.svc.cluster.local:10000"
            }
          }
        }
      }
    }
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/service_v1.json
apiVersion: v1
kind: Service
metadata:
  name: &name ts-ai3090-node
spec:
  clusterIP: None
  selector:
    app: *name
