---
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/master/statefulset.json
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: &app ts-ai3090-node
spec:
  serviceName: *app
  replicas: 1
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:
      serviceAccountName: proxies
      nodeSelector:
        feature.node.kubernetes.io/pci-10de.present: "true"
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      containers:
        - name: tailscale
          image: ghcr.io/tailscale/tailscale:v1.98.3@sha256:854b77123b9536adae2e97f5a5fdb1790ed03438b911ab7f07780155e0af6ce2
          env:
            - name: TS_KUBE_SECRET
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name  # → ts-ai3090-node-0
            - name: TS_HOSTNAME
              value: ai3090
            - name: TS_USERSPACE
              value: "true"
            - name: TS_DEBUG_FIREWALL_MODE
              value: nftables
            - name: TS_SERVE_CONFIG
              value: /serve/serve.json
          volumeMounts:
            - name: serve-config
              mountPath: /serve
          securityContext:
            privileged: true
      volumes:
        - name: serve-config
          configMap:
            name: ts-ai3090-node-serve
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ts-ai3090-node-serve
data:
  serve.json: |
    {
      "TCP": {
        "443": {
          "HTTPS": true
        }
      },
      "Web": {
        "$${TS_CERT_DOMAIN}:443": {
          "Handlers": {
            "/": {
              "Proxy": "http://llama-cpp.ai.svc.cluster.local:10000"
            }
          }
        }
      }
    }
---
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/master/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: &name ts-ai3090-node
spec:
  clusterIP: None
  selector:
    app: *name
