---
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/master/statefulset.json
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: &app ts-p1g6-egress
spec:
  serviceName: *app
  replicas: 1
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:
      serviceAccountName: proxies
      containers:
        - name: tailscale
          image: ghcr.io/tailscale/tailscale:v1.94.2@sha256:95e528798bebe75f39b10e74e7051cf51188ee615934f232ba7ad06a3390ffa1
          env:
            - name: TS_KUBE_SECRET
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name  # → ts-p1g6-egress-0
            - name: TS_TAILNET_TARGET_FQDN
              value: "p1g6.${TAILSCALE_MAGICDNS}"
            - name: TS_USERSPACE
              value: "true"
            - name: TS_DEBUG_FIREWALL_MODE
              value: nftables
          securityContext:
            privileged: true
---
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/master/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: &name ts-p1g6-egress
spec:
  clusterIP: None
  selector:
    app: *name
---
# yaml-language-server: $schema=https://github.com/yannh/kubernetes-json-schema/raw/refs/heads/master/master/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: ts-p1g6
spec:
  selector:
    app: ts-p1g6-egress
  ports:
    - port: 11434
      targetPort: 11434
