---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name hermes-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        ## API Keys
        LITELLM_API_KEY: "{{ .LITELLM_HOMELAB_KEY }}"
        HONCHO_API_KEY: "{{ .LLM_OPENAI_API_KEY }}"
        ## Connections
        GITHUB_TOKEN: "{{ .KONFLATE_TOKEN }}"
        GITHUB_APP_ID: "{{ .KONFLATE_APP_CLIENT_ID }}"
        GITHUB_APP_PRIVATE_KEY_PATH: "{{ .KONFLATE_APP_PRIVATE_KEY }}"
        #GITHUB_APP_INSTALLATION_ID: ""
        ## Hermes
        API_SERVER_KEY: "{{ .HERMES_API_SERVER_KEY }}"
  dataFrom:
    - extract:
        key: /ai/hermes
    - extract:
        key: /ai/honcho
    - extract:
        key: /ai/litellm
    - extract:
        key: /kubernetes/konflate
    - extract:
        key: /kubernetes/actions-runner
