---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name hermes-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        ## API Keys
        LITELLM_API_KEY: "{{ .LITELLM_MASTER_KEY }}"
        MEMINI_API_KEY: "{{ .MEMINI_HERMES_API_KEY }}"
        ## Connections
        SECRET_DOMAIN: "{{ .SECRET_DOMAIN }}"
        GITHUB_TOKEN: "{{ .GH_HERMES_TOKEN }}"
        # GITHUB_APP_ID: "{{ .KONFLATE_APP_CLIENT_ID }}"
        # GITHUB_APP_PRIVATE_KEY_PATH: "{{ .KONFLATE_APP_PRIVATE_KEY }}"
        # GITHUB_APP_INSTALLATION_ID: ""
        PHOTON_PROJECT_ID: "{{ .PHOTON_PROJECT_ID }}"
        PHOTON_PROJECT_SECRET: "{{ .PHOTON_PROJECT_SECRET }}"
        DISCORD_BOT_TOKEN: "{{ .DISCORD_BOT_TOKEN }}"
        DISCORD_ALLOWED_USERS: "{{ .DISCORD_ALLOWED_USERS }}"
        DISCORD_HOME_CHANNEL: "{{ .DISCORD_HOME_CHANNEL }}"
        ## Hermes
        API_SERVER_KEY: "{{ .HERMES_API_SERVER_KEY }}"
  dataFrom:
    - extract:
        key: /ai/hermes
    - extract:
        key: /ai/litellm
    - extract:
        key: /ai/memini
    - extract:
        key: /kubernetes/actions-runner
    - extract:
        key: /kubernetes/cluster-secrets
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name hermes-dashboard
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        HERMES_DASHBOARD_OIDC_CLIENT_ID: "{{ .HERMES_OIDC_CLIENT_ID }}"
        HERMES_DASHBOARD_OIDC_CLIENT_SECRET: "{{ .HERMES_OIDC_CLIENT_SECRET }}"
        HERMES_DASHBOARD_OIDC_SCOPES: "openid profile email"
        HERMES_DASHBOARD_OIDC_ISSUER: https://{{ .AUTHENTIK_SSO_SUBDOMAIN }}.${SECRET_DOMAIN}/application/o/${APP}/
        HERMES_DASHBOARD_PUBLIC_URL: https://${APP}.${SECRET_DOMAIN}
  dataFrom:
    - extract:
        key: /default/authentik
