---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/pocketid.internal/pocketidoidcclient_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: hermes
spec:
  name: Hermes
  callbackUrls:
    - "https://${APP}.${SECRET_DOMAIN}/auth/callback"
  launchUrl: "https://${APP}.${SECRET_DOMAIN}/"
  logo:
    logoUrl: "https://cdn.jsdelivr.net/gh/selfhst/icons@main/webp/hermes-agent.webp"
  pkceEnabled: true
  allowedUserGroups:
    - name: id-admin
      namespace: security
    - name: id-family
      namespace: security
  secret:
    enabled: true
    name: hermes-oidc-secret
    keys:
      clientID: HERMES_DASHBOARD_OIDC_CLIENT_ID
      clientSecret: HERMES_DASHBOARD_OIDC_CLIENT_SECRET
      issuerUrl: HERMES_DASHBOARD_OIDC_ISSUER
