---
# This file is not managed by doco-cd because it can't manage itself.
# A cron job on TrueNAS pulls `docker-compose.app.yaml` and `Dockerfile`
# from GitHub, compares hashes, and rebuilds only when something changed.

secrets:
  gh_token:
    file: /mnt/nas/data/users/sysadmin/.config/doco-cd/gh_token

services:
  doco-cd:
    image: ghcr.io/kimdre/doco-cd:0.82.0-rc.1@sha256:4a5e231a020a2527118cdfdf10097052f91d04fb5c0414f71aa47422c7ddc7a4
    container_name: doco-cd
    restart: unless-stopped
    networks:
      - doco-cd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - data:/data
    env_file:
      - path: /mnt/nas/data/users/sysadmin/.config/doco-cd/.env
        required: true
    environment:
      LOG_LEVEL: info
      DEPLOY_CONFIG_BASE_DIR: ./docker/truenas/
      POLL_CONFIG: |-
        - url: https://github.com/tscibilia/home-ops.git
          reference: refs/heads/main
          interval: 3600
      SECRET_PROVIDER: webhook
      SECRET_PROVIDER_WEBHOOK_STORES: |
        name: akeyless
        version: v1
        url: "https://api.akeyless.io/v2/get-secret-value"
        method: POST
        headers:
          Content-Type: application/json
          Authorization: "Basic {{ print .auth.username \":\" .auth.password | b64enc }}"
        body: '{"secret_name":"{{ .remote_ref.key }}","auth_method_access_token":"{{ .auth.token }}"}'
        json_path: "value"
      SECRET_PROVIDER_AUTH_USERNAME: ${AKEYLESS_ACCESS_ID}
      SECRET_PROVIDER_AUTH_PASSWORD: ${AKEYLESS_ACCESS_KEY}
      TZ: America/New_York
    cap_drop:
      - ALL
    healthcheck:
      test:
        - CMD
        - /doco-cd
        - healthcheck
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    secrets:
      - gh_token

networks:
  doco-cd:
    external: true

volumes:
  data: {}
