---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/grafana.integreatly.org/grafanaalertrulegroup_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaAlertRuleGroup
metadata:
  name: plex-alerts
spec:
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  folderUID: Logs
  interval: 5m
  rules:
    - uid: plex-database-busy
      title: PlexDatabaseIsBusy
      condition: C
      data:
        - refId: A
          queryType: range
          relativeTimeRange:
            from: 300
            to: 0
          datasourceUid: victorialogs
          model:
            expr: |
              app: "plex"
              | _msg:~"retry busy DB"
            intervalMs: 60000
            maxDataPoints: 43200

        - refId: B
          queryType: ""
          relativeTimeRange:
            from: 300
            to: 0
          datasourceUid: __expr__
          model:
            type: reduce
            expression: A
            reducer: count

        - refId: C
          queryType: ""
          relativeTimeRange:
            from: 300
            to: 0
          datasourceUid: __expr__
          model:
            type: threshold
            expression: B
            conditions:
              - evaluator:
                  params:
                    - 0
                  type: gt
                operator:
                  type: and
      annotations:
        description: "plex is experiencing database issues"
      labels:
        severity: critical
        app: plex
      for: 1m
      noDataState: OK
      execErrState: Alerting
