---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name pangolin-operator-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        PANGOLIN_API_URL: "https://tun.t0m.co"
        PANGOLIN_API_KEY: "{{ .api_key }}"
        PANGOLIN_ENDPOINT: "tun.t0m.co"
        PANGOLIN_ORG_ID: "homelab"
  data:
    - secretKey: api_key
      remoteRef:
        key: kubernetes/network/pangolin-operator/api-key
