name: unfbkup

services:
  ofelia:
    image: docker.io/mcuadros/ofelia:0.3.22@sha256:0aeec97f549d3cae77cd5a926001d5beeac3aa91e69363f9db1e85851c091328
    container_name: ofelia
    restart: unless-stopped
    command: daemon --docker
    depends_on:
      - unifi-backup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  unifi-backup:
    image: docker.io/restic/restic:0.18.1@sha256:b43f00a24d9b2d9affb332a29d57042563eeb61219ae1a36dfccbdc34fbaa6b3
    container_name: unifi-backup
    restart: unless-stopped
    entrypoint: /bin/sh
    command: ["-c", "sleep infinity"]
    volumes:
      - /opt/unifi/config:/config:ro
    environment:
      RESTIC_REPOSITORY: ${RESTIC_REPOSITORY}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      B2_ACCOUNT_ID: ${B2_ACCOUNT_ID}
      B2_ACCOUNT_KEY: ${B2_ACCOUNT_KEY}
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.backup.schedule: "0 0 3 * * *"
      ofelia.job-exec.backup.command: "sh -c 'restic backup /config && restic forget --keep-daily 7 --keep-weekly 4 --prune'"

networks:
  default:
    name: pangolin
    external: true
