name: unfbkup

services:
  ofelia:
    image: docker.io/mcuadros/ofelia:v0.3.9@sha256:aa1b935ed0d7d01805bb9ca95e7b44499208ad8d95016d6afa8fdf967ea65c74
    container_name: ofelia
    restart: unless-stopped
    command: daemon --docker
    depends_on:
      - unifi-backup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  unifi-backup:
    image: docker.io/restic/restic:0.17.3@sha256:80361423ec2beca5646ff0a94aed3f28ac9ad7a6742fb24f66e617359b9754ce
    container_name: unifi-backup
    restart: unless-stopped
    entrypoint: /bin/sh
    command: ["-c", "sleep infinity"]
    volumes:
      - /opt/unifi/config:/config:ro
    environment:
      RESTIC_REPOSITORY: ${RESTIC_REPOSITORY}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      B2_ACCOUNT_ID: ${B2_ACCOUNT_ID}
      B2_ACCOUNT_KEY: ${B2_ACCOUNT_KEY}
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.backup.schedule: "0 0 3 * * *"
      ofelia.job-exec.backup.command: "sh -c 'restic backup /config && restic forget --keep-daily 7 --keep-weekly 4 --prune'"

networks:
  default:
    name: pangolin
    external: true
