name: unfbkup

services:
  ofelia:
    image: docker.io/mcuadros/ofelia:v3.0.8@sha256:2e0c1a420bbc09868fcfaf6c3596e4b275ced912cc45f8cbe1b9c09abaea8a7f
    container_name: ofelia
    restart: unless-stopped
    command: daemon --docker
    depends_on:
      - unifi-backup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  unifi-backup:
    image: docker.io/restic/restic:0.19.0@sha256:823d7643f3591e17cb98ef476924827a03f0d47076ac8a692029ac2cab55251b
    container_name: unifi-backup
    restart: unless-stopped
    entrypoint: /bin/sh
    command: ["-c", "sleep infinity"]
    volumes:
      - /opt/unifi/config:/config:ro
    environment:
      RESTIC_REPOSITORY: ${RESTIC_REPOSITORY}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      B2_ACCOUNT_ID: ${B2_ACCOUNT_ID}
      B2_ACCOUNT_KEY: ${B2_ACCOUNT_KEY}
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.backup.schedule: "0 0 3 * * *"
      ofelia.job-exec.backup.command: "sh -c 'restic backup /config && restic forget --keep-daily 7 --keep-weekly 4 --prune'"

networks:
  default:
    name: pangolin
    external: true
