---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name home-assistant-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        HASS_DARKSKY_API_KEY: "{{ .HASS_DARKSKY_API_KEY }}"
        HASS_ECOBEE_API_KEY: "{{ .HASS_ECOBEE_API_KEY }}"
        HASS_ELEVATION: "{{ .HASS_ELEVATION }}"
        HASS_LATITUDE_HOME: "{{ .HASS_LATITUDE_HOME }}"
        HASS_LONGITUDE_HOME: "{{ .HASS_LONGITUDE_HOME }}"
        HASS_WEATHER_UNDERGROUND_API_KEY: "{{ .HASS_WEATHER_UNDERGROUND_API_KEY }}"
        HASS_GOOGLE_TRAVEL_API: "{{ .HASS_GOOGLE_TRAVEL_API }}"
  dataFrom:
    - extract:
        key: /home-assistant
