---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name boxbox-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        BOXBOX_USERS_sysadmin: "{{ .FILEBROWSER_ADMIN_PASSWORD }}"
        BOXBOX_JWT_SECRET: "{{ .BOXBOX_JWT_SECRET }}"
  dataFrom:
    - extract:
        key: /default/filebrowser
