---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name fairtrail-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        DATABASE_URL: "postgresql://${APP}:{{ .${APP}_postgres_password }}@${CNPG_NAME}-rw.database.svc.cluster.local:5432/${APP}"
        ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
        ADMIN_SESSION_SECRET: "{{ .ADMIN_SESSION_SECRET }}"
        CRON_SECRET: "{{ .CRON_SECRET }}"
  dataFrom:
    - extract:
        key: /cnpg-users
    - extract:
        key: /default/fairtrail
