---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name dragonfly-secret
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .B2_T0MKUBE_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .B2_T0MKUBE_SECRET_ACCESS_KEY }}"
        AWS_ENDPOINT: "{{ .B2_ENDPOINT }}"
        AWS_REGION: "{{ .B2_REGION }}"
        AWS_REDIS_BUCKET: "{{ .B2_REDIS_BUCKET }}"
  dataFrom:
    - extract:
        key: /cloud-providers/b2-creds
