---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/pocketid.internal/pocketidoidcclient_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: homepage
spec:
  name: Homepage
  callbackUrls:
    - "https://${GATUS_SUBDOMAIN}.${SECRET_DOMAIN}/api/auth/callback/homepage-oidc"
  launchUrl: "https://${GATUS_SUBDOMAIN}.${SECRET_DOMAIN}/"
  pkceEnabled: true
  allowedUserGroups:
    - name: id-admin
      namespace: security
    - name: id-home
      namespace: security
  secret:
    enabled: true
    name: homepage-oidc-secret
    keys:
      clientID: HOMEPAGE_OIDC_CLIENT_ID
      clientSecret: HOMEPAGE_OIDC_CLIENT_SECRET
      issuerUrl: HOMEPAGE_OIDC_ISSUER
