---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name tailscale-operator-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        client_id: "{{ .TS_OPER_OAUTH_CLIENT_ID }}"
        client_secret: "{{ .TS_OPER_OAUTH_CLIENT_SECRET }}"
        # Secret used via subsituteFrom for proxyConfig files
        TAILSCALE_MAGICDNS: "{{ .TS_OPER_MAGICDNS }}"
  dataFrom:
    - extract:
        key: /network/tailscale/operator
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    creationPolicy: Orphan # ESO will create if it doesn't exist, but won't overwrite/delete it
    template:
      data:
        _current-profile: "{{ .TS_OPER_CURRENT_PROFILE }}"
        _machinekey: "{{ .TS_OPER_MACHINEKEY }}"
        _profiles: "{{ .TS_OPER_PROFILES }}"
        profile-db48: "{{ .TS_OPER_PROFILE_DATA }}"   # This suffix will change if it re-registers
  dataFrom:
    - extract:
        key: /network/tailscale/operator
