---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name tailscale-operator-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        client_id: "{{ .TS_OPER_OAUTH_CLIENT_ID }}"
        client_secret: "{{ .TS_OPER_OAUTH_CLIENT_SECRET }}"
        # Secret used via subsituteFrom for proxyConfig files
        TAILSCALE_MAGICDNS: "{{ .TS_OPER_MAGICDNS }}"
  dataFrom:
    - extract:
        key: /network/tailscale/operator
