---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tailscale-operator
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    # Not supported in this chart version, use postRenderers
    # fullnameOverride: tailscale-operator
    operatorConfig:
      hostname: *app
      podAnnotations:
        secret.reloader.stakater.com/reload: &secret tailscale-operator-secret
    proxyConfig:
      defaultTags: "tag:k8s"
    apiServerProxyConfig:
      mode: "true"
  valuesFrom:
    - kind: Secret
      name: *secret
      valuesKey: client_id
      targetPath: oauth.clientId
    - kind: Secret
      name: *secret
      valuesKey: client_secret
      targetPath: oauth.clientSecret
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: operator
            patch: |
              - op: replace
                path: /metadata/name
                value: tailscale-operator
