---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: &name immich-oidc-secret
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: akeyless-secret-store
  selector:
    secret:
      name: *name
  data:
    - match:
        secretKey: IMMICH_OIDC_CLIENT_ID
        remoteRef:
          remoteKey: /security/pocket-id-clients
          property: IMMICH_OIDC_CLIENT_ID
    - match:
        secretKey: IMMICH_OIDC_CLIENT_SECRET
        remoteRef:
          remoteKey: /security/pocket-id-clients
          property: IMMICH_OIDC_CLIENT_SECRET
    - match:
        secretKey: IMMICH_OIDC_ISSUER_URL
        remoteRef:
          remoteKey: /security/pocket-id-clients
          property: IMMICH_OIDC_ISSUER_URL
