---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kokoro
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 1h
  values:
    controllers:
      *app :
        containers:
          app:
            image:
              repository: ghcr.io/remsky/kokoro-fastapi-cpu
              tag: v0.9.0@sha256:ee3111d6a2c903ed62f3b4fa19543c6901205ed39fce3c177e895b34a8386b9c
            env:
              PORT: &port 8880
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec: &probeSpec
                  httpGet:
                    path: /health
                    port: *port
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                <<: *probes
                spec:
                  <<: *probeSpec
                  periodSeconds: 10
            resources:
              requests:
                cpu: 10m
                memory: 1Gi
              limits:
                memory: 3Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    route:
      ui:
        enabled: true
        hostnames: ["${GATUS_SUBDOMAIN}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      cache:
        existingClaim: *app
        globalMounts:
          - path: /app/cache
