---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.config.k8s.io/kustomization_v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./model.yaml
  - ./inferenceservice.yaml
  - ./service.yaml
  - ./httproute.yaml
  - ./pvc.yaml
configMapGenerator:
  - name: comfyui-configmap
    files:
      - ./resources/config.ini
  - name: comfyui-idle-probe
    files:
      - ./resources/idle-probe.py
generatorOptions:
  disableNameSuffixHash: true
