---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name open-webui-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        OPENAI_API_KEYS: "{{ .LITELLM_OPENWEBUI_AGENTKEY }}"
        # LITELLM_MCP_API_KEY: "{{ .LITELLM_HOMELAB_KEY }}"
        WEBUI_SECRET_KEY: "{{ .OPENAI_WEBUI_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: /ai/open-webui
    - extract:
        key: /ai/litellm
