---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name tududi-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        TUDUDI_SESSION_SECRET: "{{ .TUDUDI_SESSION_SECRET }}"
        OIDC_CLIENT_ID: "{{ .TUDUDI_OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .TUDUDI_OIDC_CLIENT_SECRET }}"
        OIDC_ISSUER_URL: "https://{{ .AUTHENTIK_SSO_SUBDOMAIN }}.${SECRET_DOMAIN}/application/o/${APP}/"
  dataFrom:
    - extract:
        key: /default/tududi
    - extract:
        key: /default/authentik
