# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name honcho-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        DB_CONNECTION_URI: "postgresql+psycopg://honcho:{{ .honcho_postgres_password }}@pgvector-cluster-rw.database.svc.cluster.local:5432/honcho"
        LLM_OPENAI_API_KEY: "{{ .LLM_OPENAI_API_KEY }}"
        VECTOR_STORE_TYPE: "{{ .VECTOR_STORE_TYPE }}"
        DERIVER_MODEL_CONFIG__TRANSPORT: &openai "{{ .DERIVER_MODEL_CONFIG__TRANSPORT }}"
        DERIVER_MODEL_CONFIG__MODEL: &model "{{ .DERIVER_MODEL_CONFIG__MODEL }}"
        DERIVER_MODEL_CONFIG__OVERRIDES__BASE_URL: &base-url "{{ .DERIVER_MODEL_CONFIG__OVERRIDES__BASE_URL }}"
        SUMMARY_MODEL_CONFIG__TRANSPORT: *openai
        SUMMARY_MODEL_CONFIG__MODEL: *model
        SUMMARY_MODEL_CONFIG__OVERRIDES__BASE_URL: *base-url
        DIALECTIC_LEVELS__minimal__MODEL_CONFIG__TRANSPORT: *openai
        DIALECTIC_LEVELS__minimal__MODEL_CONFIG__MODEL: *model
        DIALECTIC_LEVELS__minimal__MODEL_CONFIG__OVERRIDES__BASE_URL: *base-url
        DIALECTIC_LEVELS__low__MODEL_CONFIG__TRANSPORT: *openai
        DIALECTIC_LEVELS__low__MODEL_CONFIG__MODEL: *model
        DIALECTIC_LEVELS__low__MODEL_CONFIG__OVERRIDES__BASE_URL: *base-url
        DIALECTIC_LEVELS__medium__MODEL_CONFIG__TRANSPORT: *openai
        DIALECTIC_LEVELS__medium__MODEL_CONFIG__MODEL: *model
        DIALECTIC_LEVELS__medium__MODEL_CONFIG__OVERRIDES__BASE_URL: *base-url
        DIALECTIC_LEVELS__high__MODEL_CONFIG__TRANSPORT: *openai
        DIALECTIC_LEVELS__high__MODEL_CONFIG__MODEL: *model
        DIALECTIC_LEVELS__high__MODEL_CONFIG__OVERRIDES__BASE_URL: *base-url
        DIALECTIC_LEVELS__max__MODEL_CONFIG__TRANSPORT: *openai
        DIALECTIC_LEVELS__max__MODEL_CONFIG__MODEL: *model
        DIALECTIC_LEVELS__max__MODEL_CONFIG__OVERRIDES__BASE_URL: *base-url
  dataFrom:
    - extract:
        key: /ai/honcho
    - extract:
        key: /database/cnpg-users
